// Code generated by "stringer -type=ChartType -output=chart_type_string.go"; DO NOT EDIT.

package charts

import "fmt"

const _ChartType_name = "UnknownChartSimpleBarSimpleLineGroupedBarMultiLine"

var _ChartType_index = [...]uint8{0, 12, 21, 31, 41, 50}

func (i ChartType) String() string {
	if i < 0 || i >= ChartType(len(_ChartType_index)-1) {
		return fmt.Sprintf("ChartType(%d)", i)
	}
	return _ChartType_name[_ChartType_index[i]:_ChartType_index[i+1]]
}
