// Code generated by "stringer -type=DataType -output=data_type_string.go"; DO NOT EDIT.

package charts

import "fmt"

const _DataType_name = "UnknownTypeTextNumberTime"

var _DataType_index = [...]uint8{0, 11, 15, 21, 25}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return fmt.Sprintf("DataType(%d)", i)
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
